export default [
  {
    ignores: ['archive/', 'portable/', 'scripts/'],
  },
  {
    files: ['public/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      globals: {
        document: 'readonly',
        window: 'readonly',
        console: 'readonly',
        fetch: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        localStorage: 'readonly',
        location: 'readonly',
        MouseEvent: 'readonly',
        KeyboardEvent: 'readonly',
        FileReader: 'readonly',
        Image: 'readonly',
        URL: 'readonly',
        NodeList: 'readonly',
        HTMLDocument: 'readonly',
        CustomEvent: 'readonly',
      },
      parserOptions: {
        sourceType: 'script',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { vars: 'all', args: 'none' }],
      'no-undef': 'error',
      'no-var': 'warn',
      'prefer-const': 'warn',
      'no-empty': 'warn',
      'no-dupe-keys': 'error',
      'no-constant-condition': 'warn',
      'no-unreachable': 'warn',
      'no-extra-semi': 'warn',
      'semi': ['warn', 'always'],
      'quotes': ['warn', 'single', { avoidEscape: true }],
      'eqeqeq': ['warn', 'smart'],
      'curly': ['warn', 'multi'],
      'no-trailing-spaces': 'warn',
    },
  },
];
